tcib_actions:
- run: if [ -f "/etc/yum.repos.d/ubi.repo" ]; then rm -f /etc/yum.repos.d/ubi.repo && dnf clean all && rm -rf /var/cache/dnf; fi
- run: if [ -f "/etc/yum.repos.d/centos.repo" ]; then rm -f /etc/yum.repos.d/centos*.repo && dnf clean all && rm -rf /var/cache/dnf; fi
- run: >-
    dnf install -y crudini &&
    crudini --del /etc/dnf/dnf.conf main override_install_langs &&
    crudini --set /etc/dnf/dnf.conf main clean_requirements_on_remove True &&
    crudini --set /etc/dnf/dnf.conf main exactarch 1 &&
    crudini --set /etc/dnf/dnf.conf main gpgcheck 1 &&
    crudini --set /etc/dnf/dnf.conf main install_weak_deps False &&
    if [ '{{ tcib_distro }}' == 'centos' ];then crudini --set /etc/dnf/dnf.conf main best False; fi &&
    crudini --set /etc/dnf/dnf.conf main installonly_limit 0 &&
    crudini --set /etc/dnf/dnf.conf main keepcache 0 &&
    crudini --set /etc/dnf/dnf.conf main obsoletes 1 &&
    crudini --set /etc/dnf/dnf.conf main plugins 1 &&
    crudini --set /etc/dnf/dnf.conf main skip_missing_names_on_install False &&
    crudini --set /etc/dnf/dnf.conf main tsflags nodocs
- run: dnf install -y {{ tcib_packages['common'] | join(' ') }} {{ tcib_package }}
- run: if [ ! -f "/etc/pki/tls/cert.pem" ]; then ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/pki/tls/cert.pem; fi
- run: cp /usr/share/tcib/container-images/kolla/base/uid_gid_manage.sh /usr/local/bin/uid_gid_manage
- run: chmod 755 /usr/local/bin/uid_gid_manage
- run: bash /usr/local/bin/uid_gid_manage kolla hugetlbfs libvirt qemu
- run: touch /usr/local/bin/kolla_extend_start && chmod 755 /usr/local/bin/kolla_extend_start
- run: cp /usr/share/tcib/container-images/kolla/base/set_configs.py /usr/local/bin/kolla_set_configs
- run: chmod 755 /usr/local/bin/kolla_set_configs
- run: cp /usr/share/tcib/container-images/kolla/base/start.sh /usr/local/bin/kolla_start
- run: chmod 755 /usr/local/bin/kolla_start
- run: cp /usr/share/tcib/container-images/kolla/base/httpd_setup.sh /usr/local/bin/kolla_httpd_setup
- run: chmod 755 /usr/local/bin/kolla_httpd_setup
- run: cp /usr/share/tcib/container-images/kolla/base/copy_cacerts.sh /usr/local/bin/kolla_copy_cacerts
- run: chmod 755 /usr/local/bin/kolla_copy_cacerts
- run: cp /usr/share/tcib/container-images/kolla/base/sudoers /etc/sudoers
- run: chmod 440 /etc/sudoers
- run: sed -ri '/^(passwd:|group:)/ s/systemd//g' /etc/nsswitch.conf
- run: >-
    dnf -y reinstall which &&
    rpm -e --nodeps tzdata &&
    dnf -y install tzdata
- run: mkdir -p /openstack
- run: >-
    if [ '{{ tcib_distro }}' == 'centos' ];then
    if [ -n "$(rpm -qa redhat-release)" ];then rpm -e --nodeps redhat-release; fi ;
    dnf -y install centos-stream-release; fi
- run: dnf update --excludepkgs redhat-release -y && dnf clean all && rm -rf /var/cache/dnf
tcib_cmd: kolla_start
tcib_entrypoint: dumb-init --single-child --
tcib_envs:
  LANG: en_US.UTF-8
  container: oci
tcib_labels:
  maintainer: OpenStack Kubernetes Operator team
  tcib_managed: True
tcib_packages:
  common:
  - ca-certificates
  - dumb-init
  - glibc-langpack-en
  - procps-ng
  - python3
  - sudo
  - util-linux-user
  - which
tcib_stopsignal: SIGTERM
